### ISSUE TITLE
训练时长

### ISSUE THREAD

**Issue by HCL0708** [Fediory/HVI-CIDNet#10]
作者您好，请问您训练lolv1的模型在单个3090上花费了多长时间

**Comment by Fediory** [comment]
您好，我们在LOLv1上训练的时长取决于epoch和batch size的选择，一般为3h-12h不等。当设置batch=5，epoch=1000时，约4到6小时即可完成训练。如果您觉得我们的工作对您有帮助，麻烦点个Star，谢谢！
