### ISSUE TITLE
在测试集上进行微调是什么意思

### ISSUE THREAD

**Issue by HCL0708** [Fediory/HVI-CIDNet#11]
![image](https://github.com/Fediory/HVI-CIDNet/assets/104913310/7f54be22-ccdb-43dd-a7a1-ecc436fa1d47)
作者您好，如图所示，你在项目中对测试集进行了微调是什么意思？做了怎样的微调？

**Comment by Fediory** [comment]
这里是指在训练的时候，针对Test测试集进行了额外的训练，以达到更好的PSNR，但这其实无法证明一个模型究竟好不好，因此我们不推荐这么做。

**Comment by HCL0708** [comment]
> 这里是指在训练的时候，针对Test测试集进行了额外的训练，以达到更好的PSNR，但这其实无法证明一个模型究竟好不好，因此我们不推荐这么做。

作者您好，我重新训练了您的代码在lolv1数据集上，使用的是代码中的默认setting，但是不使用perceptual loss的结果和您论文中使用perceptual loss的结果是差不多的，并没有达到您论文中不使用perceptual loss的效果

**Comment by Fediory** [comment]
我们所提供的配置是一个普适性配置，即这个配置可能复现出我们的weights，但是需要运气（尤其是在LOLv1这个仅有15张图片的测试集上）。如果无法复现，可以对我们的配置进行修改，比如针对LOLv1，我们推荐降低batch size，提高crop size。

**Comment by HCL0708** [comment]
> 我们所提供的配置是一个普适性配置，即这个配置可能复现出我们的weights，但是需要运气（尤其是在LOLv1这个仅有15张图片的测试集上）。如果无法复现，可以对我们的配置进行修改，比如针对LOLv1，我们推荐降低batch size，提高crop size。

作者您好，我想问一下每个数据集训练时的corp size是不是一样的，我看论文中只写了crop size为256

**Comment by HCL0708** [comment]
@Fediory 作者您好，我在使用您提供的权重进行测试时，发现(LOLv1) v1 wo perc loss/ w gt mean这一个的psnr比您的结果(28.1405)更好，达到了28.20，以及news中的2024.05.12 Update peer results on LOLv1是什么（是否是有更好的结果？）

**Comment by Fediory** [comment]
您好，对于这个问题，我们的论文中的测试，都采用将进行gt mean之后的图像保存后再重新测试。因此如果您在PSNR上测出了更好的结果，属于正常现象。我们可以确保我们的所有weights都和论文中的结果对应上。
