### ISSUE TITLE
关于您的权重问题

### ISSUE THREAD

**Issue by g483122074** [Fediory/HVI-CIDNet#17]
请问您的 LOLv1中 w_perc.pth、wo_perc.pth、 test_finetuning.pth这三个权重是如何训练出来的。在我看来只有一个train.py文件，或者说是需要改变什么其他参数吗。
同样的疑问对LOLv2中的几个不同权重也有。
如果您能解答我将不胜感激，已经给了star谢谢！

**Comment by Fediory** [comment]
您可以查看`data/options.py`中的代码，里面包含所有的超参数(default)。我们感谢您对我们工作的支持！
