### ISSUE TITLE
关于多次训练结果相差较大的问题

### ISSUE THREAD

**Issue by shaofei2019** [Fediory/HVI-CIDNet#18]
目的：我在您的模型中引入了其他的模块，验证该模块的有效性

问题：对您分享的模型和我修改过后的模型分别进行了几次训练，对于同一个模型，均采用lolv1作为训练集，几次训练结果相差都比较大，这种现象是不是数据集数量少导致的？使用其他图像数量较多的数据集是否能够一定程度避免这种现象，从而有利于判断引入模块的有效性？

对此，请问您有什么经验可以分享一下吗？

**Comment by Fediory** [comment]
根据我过去的经验，我可以确定这是LOLv1数据集test较少导致的。我推荐您选择更稳定的LOLv2数据集，里面包含两个子数据集，都有100张图片作为test。

**Comment by shaofei2019** [comment]
> 根据我过去的经验，我可以确定这是LOLv1数据集test较少导致的。我推荐您选择更稳定的LOLv2数据集，里面包含两个子数据集，都有100张图片作为test。

感谢您的回答

**Comment by InCloudsBelly** [comment]
但是实际上LOLv2的训练集中有非常多的过度黑暗或者噪声很大的训练图像，这也是你们选择使用单个Perceptual Loss作为loss的原因吗？

**Comment by Fediory** [comment]
Perceptual Loss包含语义信息，它的确可以大幅降低图像噪声，让整个图片感知度更强。但是过度黑暗问题和这个Loss并没有直接关系。LOLv2我们使用单个Perceptual Loss主要只是因为它包含语义信息，且在HVI和RGB空间都使用这个Loss的PSNR会更好更稳定。
