### ISSUE TITLE
LOLv2_syn训练问题

### ISSUE THREAD

**Issue by g483122074** [Fediory/HVI-CIDNet#20]
我在训练LOLv2_syn时出现如下错误
![A(2{463F JY6LYLQ6D(N 7P](https://github.com/Fediory/HVI-CIDNet/assets/129936487/efff8b8f-d424-4883-ab92-933465499e40)

但是训练其他数据集时却没有该问题。请问你们是否可以提供一些可能得原因。

**Comment by g483122074** [comment]
此问题已解决，我将norml中的图像名称改为与low中的一致之后恢复了正常

**Comment by g483122074** [comment]
有时那个进度条可以到达三十多或者五十多报错，但始终卡在这一步。即开始训练的第一步

**Comment by Fediory** [comment]
请问现在这个错误还存在吗

**Comment by g483122074** [comment]
您好，这个问题依旧存在，并且令我感到困惑的是，相同设置下其他数据集却没有问题

**Comment by g483122074** [comment]
> 请问现在这个错误还存在吗

您好，这个问题依旧存在，并且令我感到困惑的是，相同设置下其他数据集却没有问题

**Comment by g483122074** [comment]
> 请问现在这个错误还存在吗

并且每次报错停止时的进度条并不完全一样

**Comment by Fediory** [comment]
这个错误是由于torch.sqrt函数的梯度爆炸导致，可以在后面加一个极小量，比如1e-8。这个函数在`net/HVI_transform.py`中出现过，我们已经在刚才修复了这个问题，请重新pull

**Comment by Klawens** [comment]
解决不了，所有的数据集都会爆炸
