### ISSUE TITLE
关于TABLE I中Restormer的测试代码和权重

### ISSUE THREAD

**Issue by jingxiLiao** [Fediory/HVI-CIDNet#22]
祝贺你们，很高兴看到这么优秀的工作。另外，我一直没有找到Restormer在LOL系列（LOLv1,LOLv2）数据集的开源权重和代码，你们愿意分享一下来源吗？

**Comment by Fediory** [comment]
而对于Restormer训练的权重，目前已经有一些在Low Light Enhancement任务上的版本。我们也更推荐您去使用原始Restormer在Deblur任务上的代码，在Low Light Enhancement任务上训练一次，这样更会有说服力。
