### ISSUE TITLE
关于LOL_v1数据集eval.py测试结果问题

### ISSUE THREAD

**Issue by dadaplm** [Fediory/HVI-CIDNet#26]
对LOL_v1数据集进行测试时，使用“w_perc.pth”权重生成的“Results”图片结果与提供的“Results”图片差别较大，进一步导致PSNR、SSIM的测试结果与论文所给结果相差较大
本地生成的“Results”图片：
![1](https://github.com/user-attachments/assets/9228007c-1cc5-4955-bbfc-9f48ecd5712c)

提供的“Results”图片：
![1](https://github.com/user-attachments/assets/050734e2-7c9e-4ef9-8778-030b7bf862e8)

![1](https://github.com/user-attachments/assets/33c76a0c-dc25-4483-8cb8-cdf734f6c26d)

请问这个该如何解决？

**Comment by Fediory** [comment]
抱歉已经修复好了，请重新pull仓库
