### ISSUE TITLE
测试结果和文章的结果不一样

### ISSUE THREAD

**Issue by cjl506** [Fediory/HVI-CIDNet#27]
请问能否把您的环境贴一下，或者是否可以公开一下您再lolv1和lolv2的测试结果呢

**Comment by Fediory** [comment]
readme中已经有详细说明

**Comment by climberwu** [comment]
你好，您的论文发表之后，会不会将具体参数公开呢，想以这个作为baseline，感谢大佬公开代码！！！！

**Comment by Fediory** [comment]
> 你好，您的论文发表之后，会不会将具体参数公开呢，想以这个作为baseline，感谢大佬公开代码！！！！

很感谢您对本工作的关注。我们已经将模型参数保存到pth文件中，您可以在readme中的网盘里找到并下载使用。
