### ISSUE TITLE
How can we finetune on custom dataset

### ISSUE THREAD

**Issue by anandguptatoothlens** [Fediory/HVI-CIDNet#28]
Hi @Fediory I tried to finetune with custom dataset, but  I am getting high luminance effect, and please suggest how can i tune as lolv2_syn model.

**Comment by Fediory** [comment]
Can you show me some images of high luminance effect on your testcase?

**Comment by anandguptatoothlens** [comment]
![image](https://github.com/user-attachments/assets/7d0b2466-0a81-425c-9b9b-5d60f5457276)
![Screenshot 2024-08-13 161659](https://github.com/user-attachments/assets/9753a359-d5a0-41fe-9f97-a855be0db5b6)

**Comment by anandguptatoothlens** [comment]
I have solved. there was an issue with my dataset, Thanks
