### ISSUE TITLE
About the evaluation on LOL-Blur 

### ISSUE THREAD

**Issue by Gitlyz007** [Fediory/HVI-CIDNet#30]
When I tried to follow its results on LOL-Blur, I noticed that CIDNet uses "low_blur" as the input for training and inferencing instead of the "low_blur_noise" folder in the LOL-Blur dataset.

I found this to be a different experimental setup from existing methods (i.e., LEDNet, VQCNIR) designed for joint low-light enhancement and deblurring. Does this mean that CIDNet is based on the noise-free assumption?

If I want to train your model with ‘low_blur_noise’ and ‘high_sharp_scaled,’ can I just use the configuration of LOL-Blur in the GitHub repo?

I would appreciate it if you could provide any valuable information :)

**Comment by Fediory** [comment]
For the first question, the answer is no. The LOL dataset itself already contains real noise in low-light environments, and the same is true for the Real dataset in LOLv2. Whereas the noise of low_blur_noise in LOL-Blur is simulation-generated, we believe that LOL and LOLv2 are sufficient to demonstrate CIDNet's ability to eliminate real-world noise.

For the second question, you just need to change the path of `low_blur` to the path of your `low_blur_noise`. The easiest way to do this is to replace all the images in `low_blur` with `low_blur_noise` in the LOL_blur folder, in the train,test,eval folders, and you won't have to change any code.

**Comment by Gitlyz007** [comment]
Thanks for your patience
