### ISSUE TITLE
标签

### ISSUE THREAD

**Issue by zaoruis** [Fediory/HVI-CIDNet#32]
你好，我刚接触这个领域，有一个问题。我在paper with code发现您的代码有一个“Use GT Mean”，这是什么意思？

**Comment by Fediory** [comment]
请查看`measure.py`的99行的代码。这是一种测试方法，目的是将output与groundtruth的光照匹配后，去测试PSNR等指标。因为这个任务的目的是将低光图像增亮到合适的光照下，所以我们进行了一次简单的光照匹配。
