### ISSUE TITLE
test image shape

### ISSUE THREAD

**Issue by yjdzyr** [Fediory/HVI-CIDNet#33]
作者，您好，非常感谢作者提供这个优秀的项目！但是我在使用预训练的权重测试自己的数据集的时候发现了前向反馈的张量会在Cat的时候有大小不匹配的问题，请问这样的问题如果修改呢？
以下为问题。
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 138 but got size 139 for tensor number 1 in the list.
我也尝试resize，但是发现resize后输出的结果，并不是正常的图像。
非常期待作者的回复！

**Comment by Fediory** [comment]
首先确保您的数据集图像是的长和宽都是8的倍数，因为我们有三次下采样。如果您的图像长宽不是8的倍数，那么请padding边缘到8的倍数后，再输入到我们的模型中，最后输出时，把多余的边缘裁切掉。
