### ISSUE TITLE
how to use pretrained for custom dataset

### ISSUE THREAD

**Issue by trongldwork** [Fediory/HVI-CIDNet#34]
i have a yolo image datasets, i want to inhance it not by training, how to prepare it and inference

**Comment by Fediory** [comment]
You can eval in the Custome Datasets ways us follows
`python eval.py --unpaired --custome --custome_path ./your/costome/dataset/path --unpaired_weights ./weights/LOLv2_syn/w_perc.pth --alpha 0.9`

`alpha` is a light adjust weight. Higher is lighter
`unpaired_weights ` is the path of our model weights, which you can choose what you want (detailed in Readme).
Change `custome_path` to your YOLO path.

**Comment by Fediory** [comment]
We've uploaded the model demo to the [hugging face website](https://huggingface.co/spaces/Fediory/HVI-CIDNet_Low-light-Image-Enhancement_), feel free to use it.
