### ISSUE TITLE
HVI 色彩空间在其他图像增强任务中的应用

### ISSUE THREAD

**Issue by dawnlh** [Fediory/HVI-CIDNet#35]
非常感谢您开源的出色的工作~

想请教下您，您是否试过，HVI 色彩空间在弱光增强之外的其他low-level CV任务中，比如 风格迁移，图像美化，HDR等任务中，有没有可能带来性能提升呢？

如果是非弱光增强任务，HVI色彩空间是不是可以进行一点简化（现在有点复杂，而且有很多是专门针对弱光任务的设计）？比如去除里面的可训练参数，设计成一种和常规色彩空间（如YUV）类似的，可直接使用的色彩空间（这样HVI的作用会不会受到影响？），具体该怎么修改有没有什么建议~

谢谢！

**Comment by Fediory** [comment]
感谢您对我们工作的支持！

**Q1：HVI 色彩空间在弱光增强之外的其他low-level CV任务中？**
A1：是的，我有尝试过在图像降噪，去模糊，去雨，去雾，去鬼影使用HVI颜色空间，都有着不错的效果。其中的 CIDNet，也许要针对不同任务进行小的调整，但是不可否认 HVI 在多种任务下仍然是一个很有竞争力的颜色空间。另外，HVI比较符合人眼视觉感知，所以它的复原效果也会更贴近我们人类主观感知的效果（即使一些PSNR和SSIM数据可能不那么亮眼）。

**Q2：如果是非弱光增强任务，HVI色彩空间是不是可以进行一点简化？**
A2：
首先，我认为这是一定可以的。
我再次介绍一下 HVI 空间：它由一个 k 参数用于调整图像低光噪声密度，两个 γ 参数适配数据集相机对 RGB 三轴不同的敏感度，T(x) 是一个可自定义训练的函数，用于适配各种不同的任务。
HVI 的多种设计，与 input 到 output 的欧式距离有着密切的关系（这点我论文中没有提到，可能我会再出一篇来详细研究这个）。我们认为最小的欧式距离所带来的，一定是数据上具有更高的相似度，因此会减小网络结构的训练难度与误差。HVI 的设计与其训练参数，可以最大程度上减小 input 到 output 上的欧式空间，因此可以更好地将噪声、伪影等信息区分开。
_那么针对您的问题，我给出的解答如下：_非弱光增强的 low-level 任务，一定会有一个对退化进行建模的过程。那么 HVI 所起到的作用，就是让这个建模的过程变得更简单。如果您想修改 HVI 空间，来适配不同的任务，那么可以直接设置k，γ，T(x)三个变量为定值，保证其在这个任务的 input 到 output 平均欧式距离下最小化。如果您不知道这三个变量的最优解是什么，那么请直接设置为可训练的参数，其中T(x)可以去自行调整为一个包含参数的表达式。这样我们的颜色空间也可以针对不同的任务去详细适配了。

**Q3：可否设计成一种和常规色彩空间（如YUV）类似的，可直接使用的色彩空间？**
A3：如A2的解答一样，将变化的参数确定下来后，就会得到一个和常规颜色空间无差异的不变颜色空间。另外，所谓“颜色空间”其实是叫Color Model更为合适，因为它是由RGB空间转换而来的颜色模型，而不是相机中进行拍摄转化的真颜色空间。但是我仍然写成Color Space的原因，是因为其颜色所处的是一个正交化三维空间，写成Space会更形象些。所以，YUV与HVI只是两种不同的RGB颜色表示法，并非真正意义上的物理颜色空间。那么您多提到的可以直接使用，我更倾向于立即为参数确定的颜色空间，所以我便给出了如A2的解答。

希望我的这些解答可以帮助到您！再次感谢。

**Comment by dawnlh** [comment]
非常感谢您的详细解答，期待您新的工作
