### ISSUE TITLE
关于HVI转换

### ISSUE THREAD

**Issue by LQchen1** [Fediory/HVI-CIDNet#37]
非常出色的工作，不过我在看代码时有些疑问，论文表述的逻辑是色彩HV和光照强度I的解耦，但是我注意到在代码中HV分支还是保留了光照强度I的信息，https://github.com/Fediory/HVI-CIDNet/blob/56c94c4ff13890521965dd2c95e99b98b9787042/net/CIDNet.py#L79
我对这里不太理解，想请作者给我解答一下。
另外，我想知道论文中对于色彩空间的图是用什么软件画的呢？可以告诉我吗？

**Comment by Fediory** [comment]
色彩与光照的解耦，指的是针对channel层面的解耦，即光照和颜色信息不在同一个channel中。所以，HV两个channel代表颜色，I-channel代表光照强度。我们将其concat成三channel后，输入到hv branch，那么输入进去的也是解耦后的信息。这么做的原因是使用光照强度指导HV branch生成更精确的HV map。

另外色彩空间的图就是用python画的，这个网上可以查找的资料也比较多。

**Comment by LQchen1** [comment]
@Fediory 感谢你的解答。

**Comment by LQchen1** [comment]
好的，我目前使用python画了HSV和sRGB的图，但是我尝试根据你们论文的公式去画HVI的图，结果是失败了，请问能分享一下你们HVI空间可视化的代码吗？
![image](https://github.com/user-attachments/assets/5af1ccab-a04c-4885-b4fd-86d39ef78e2c)
![image](https://github.com/user-attachments/assets/c509231b-2e0f-426c-888b-08525af81b8c)

**Comment by Fediory** [comment]
`
# T(x)
def function(x):
    x=x/(2.0*np.pi)
    return 1

def plot_colored_ellipsoid(resolution=150, translation=(0, 0, 0)):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')

    # 创建椭球的网格，仅绘制上半球
    phi, theta = np.mgrid[0.0: 0.5 * np.pi :resolution*1j, 0.0:2.0*np.pi:resolution*1j]
    a = 1
    b = 1
    c = 1
    # 参数方程定义椭球的三维坐标
    x = a * np.sin(phi) * np.cos(theta) * function(theta)+ translation[0]
    y = b * np.sin(phi) * np.sin(theta) * function(theta)+ translation[1]
    z = c * np.sin(phi) * (np.sin(phi)**1.5)+ translation[2] # density-k

    
    # 将椭球的三维坐标转换为颜色
    h = ((theta * 180 / np.pi) % 360) /360.0  # 将横坐标映射到色相范围
    s = np.sin(phi)  # 饱和度随纬度变化
    v = np.sin(phi)  # 亮度随纬度变化
    
    # 将HSV坐标转换为RGB
    rgb_colors = hsv_to_rgb(np.dstack((h, s, v))).clip(0, 1)

    # 绘制椭球
    ax.scatter(x, y, z, c=rgb_colors.reshape((-1, 3)), s=20, marker='o', alpha=1)
    
    # 创建椭球的网格，仅绘制上半球
    r, t = np.mgrid[0.0: 1 :resolution*1j, 0.0:2.0*np.pi:resolution*1j]
    # 参数方程定义椭球的三维坐标
    x = r * np.cos(t)* function(t) + translation[0]
    y = r * np.sin(t)* function(t) + translation[1]
    z = 1 + translation[2]

    
    # 将椭球的三维坐标转换为颜色
    h = ((t * 180 / np.pi) % 360) /360.0  # 将横坐标映射到色相范围
    s = r * 2  # 饱和度随纬度变化
    v = r + 1  # 亮度随纬度变化
    
    # 将HSV坐标转换为RGB
    rgb_colors = hsv_to_rgb(np.dstack((h, s, v))).clip(0, 1)

    # 绘制顶
    ax.scatter(x, y, z, c=rgb_colors.reshape((-1, 3)), s=20, marker='o', alpha=1)

    # 设置坐标轴标签
    font2 = {'family': 'Bodoni Bd BT', 'size': 15}
    ax.set_xlabel('H',font=font2)
    ax.set_ylabel('V',font=font2)
    ax.set_zlabel('I',font=font2)
    # 设置背景为透明
    # ax.grid(False)
    # ax.set_axis_off()
    # fig.patch.set_alpha(0.0)
    ax.view_init(elev=15, azim=145) # 初始化角度
    # 显示图形
    plt.show()
    `

**Comment by Fediory** [comment]
可以参考如上代码，必要的地方已经注释
