### ISSUE TITLE
关于论文图2中的Intensity Map 和 HV Color Map如何绘制的问题

### ISSUE THREAD

**Issue by shaofei2019** [Fediory/HVI-CIDNet#40]
关于论文图2中的Intensity Map 和 HV Color Map如何绘制的问题

**Comment by Fediory** [comment]
对于Intensity Map，我使用的是热力图，亮度越高越偏向红色。
对于HV Color Map，我的画法是将sRGB转换到HVI后，将Intensity设置成恒定为1，再转换成sRGB图像。
希望这对你有帮助。

**Comment by shaofei2019** [comment]
感谢感谢
