### ISSUE TITLE
麻烦作者可以上传一下五个非配对的数据集吗

### ISSUE THREAD

**Issue by Zhouyang00** [Fediory/HVI-CIDNet#41]
作者您好！近期我发现了您这项非常优秀的工作，将会在最近我的工作中对该工作进行引用。
然而，我发现很难收集到五个未配对的数据集（DICM、LIME、MEF、NPE、VV）。所以想问您，是否方便在百度盘中更新一下这五个数据集，以方便下载。
无论结果如何，感谢您为该领域做出的贡献！

**Comment by Zhouyang00** [comment]
感谢您的回答，已star。

**Comment by climberwu** [comment]
你好，请问非配对数据集是如何进行训练的呢，求教，我看他的代码里面没有对应的训练指令
