### ISSUE TITLE
有关HSL和HVI

### ISSUE THREAD

**Issue by YYY7C** [Fediory/HVI-CIDNet#43]
非常棒的工作，在看完论文后对HVI的效果很感兴趣，个人认为HVI和HSL有点相同，但是HVI需要额外的训练，如果使用HSL进行代替是否可行？

**Comment by Fediory** [comment]
Q1：HVI是否需要额外的训练？
A1：这个其实不需要，因为他是和CIDNet同时训练的。我们只是增加了很少的参数，这个参数和后面的网络结构训练是合并起来的，不需要先训练HVI，再训练CIDNet。当然，多了这一个参数只会增加一点点时间和空间成本，这对于训练网络结构来说可以忽略不计。如果我们把这些HVI的参数都确定下来，那么其实和只训练CIDNet就没区别了，相当于是把图像换了一个颜色空间而已。

Q2：HVI和HSL的区别。
A2：
首先，我认为应该先说明HSV和HSL的区别。HSV和HSL的共同特点都是亮度与颜色相解耦，但是HSL的Lightness轴，当L=1时是一个白色平面，颜色值为FFFFFF；而L=0时又是一个黑色平面，颜色值为000000。HSV颜色空间则只有V=0时黑色平面，V=1时则是一个高光色轮。（HSV可视化如下图1，HSL可视化如下图2）（如果在网上搜到圆柱形的HSV或HSL，说明是经过极坐标化处理的，如图3为极坐标化后的HSV）

接下来，我们需要解释这个区别会带来什么影响。我们知道现在大部分数字图像都是sRGB格式存储的，包括我所使用的数据集。那么只要是颜色空间转换，无论怎么变换，都需要转换为sRGB空间去存储。这就说明，我们的增亮任务，需要选择一个更接近sRGB概率统计分布的这么一个空间，同时还要有亮度与颜色解耦合的特性。**sRGB空间的纯黑与纯白都是同一个点，如果扩张成HSL，则相当于把这两个点变成一整个平面，这无疑改变了其中的颜色空间级别的噪声与细节分布特征。而HSV则只是把黑色点摊开成平面，白色仍然是一个点。**这也就说明HSV比HSL的颜色空间级别的信噪比会更高。

最后我们说明HVI的修改方案为什么更合适。HVI是在HSV上修改得来，它的两个核心操作，一个是极坐标化，一个是黑色坍缩公式Ck。如果在HSL执行这两个操作，则无法处理白色平面问题，最后导致CIDNet提取不到关键特征。这里我们也有一些数据支持，如果您后续需要我们可以提供。
![HSV6](https://github.com/user-attachments/assets/8275d1e2-bf48-4a22-9501-8129bcd145dc)
![HSL](https://github.com/user-attachments/assets/7aade718-a1c2-49b0-b593-adacdc8e6b05)
![HSV9](https://github.com/user-attachments/assets/96e43e23-a3f9-4bb7-a83d-1c7ce05c8551)

Q3：如果使用HSL进行代替是否可行？
A3：可行，但是效果不如HVI好。这点您也可以下载我们的代码，将图像转换成HSL颜色空间进行训练，可以更直观的看到性能上的区别。我们认为颜色空间对一个模型提取信息的能力影响是非常大的，因为不同颜色空间的分布都有区别。而受限于存储图像对sRGB的依赖性，我们只能设计一个新的更接近sRGB分布，但又有亮度与颜色解耦的功能性特征的颜色空间。

希望这些回答对你有帮助。如果你认为有用也可以点点star，我们后续可能会有更新。

**Comment by YYY7C** [comment]
> Q1：HVI是否需要额外的训练？ A1：这个其实不需要，因为他是和CIDNet同时训练的。我们只是增加了很少的参数，这个参数和后面的网络结构训练是合并起来的，不需要先训练HVI，再训练CIDNet。当然，多了这一个参数只会增加一点点时间和空间成本，这对于训练网络结构来说可以忽略不计。如果我们把这些HVI的参数都确定下来，那么其实和只训练CIDNet就没区别了，相当于是把图像换了一个颜色空间而已。
> 
> Q2：HVI和HSL的区别。 A2： 首先，我认为应该先说明HSV和HSL的区别。HSV和HSL的共同特点都是亮度与颜色相解耦，但是HSL的Lightness轴，当L=1时是一个白色平面，颜色值为FFFFFF；而L=0时又是一个黑色平面，颜色值为000000。HSV颜色空间则只有V=0时黑色平面，V=1时则是一个高光色轮。（HSV可视化如下图1，HSL可视化如下图2）（如果在网上搜到圆柱形的HSV或HSL，说明是经过极坐标化处理的，如图3为极坐标化后的HSV）
> 
> 接下来，我们需要解释这个区别会带来什么影响。我们知道现在大部分数字图像都是sRGB格式存储的，包括我所使用的数据集。那么只要是颜色空间转换，无论怎么变换，都需要转换为sRGB空间去存储。这就说明，我们的增亮任务，需要选择一个更接近sRGB概率统计分布的这么一个空间，同时还要有亮度与颜色解耦合的特性。**sRGB空间的纯黑与纯白都是同一个点，如果扩张成HSL，则相当于把这两个点变成一整个平面，这无疑改变了其中的颜色空间级别的噪声与细节分布特征。而HSV则只是把黑色点摊开成平面，白色仍然是一个点。**这也就说明HSV比HSL的颜色空间级别的信噪比会更高。
> 
> 最后我们说明HVI的修改方案为什么更合适。HVI是在HSV上修改得来，它的两个核心操作，一个是极坐标化，一个是黑色坍缩公式Ck。如果在HSL执行这两个操作，则无法处理白色平面问题，最后导致CIDNet提取不到关键特征。这里我们也有一些数据支持，如果您后续需要我们可以提供。 ![HSV6](https://private-user-images.githubusercontent.com/113850295/390854501-8275d1e2-bf48-4a22-9501-8129bcd145dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDM2MTgsIm5iZiI6MTczMjg0MzMxOCwicGF0aCI6Ii8xMTM4NTAyOTUvMzkwODU0NTAxLTgyNzVkMWUyLWJmNDgtNGEyMi05NTAxLTgxMjliY2QxNDVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwMTIxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTYzNTc4MzZlMjY0YzAxYjVmNjI2ZTlhMjAyZGZmMWY5MWEwMTNjODAwZTYxZDM3ZTNkMjIyMzkzYjc5MzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.egI81NmROPmwGsNUnvoxDdcYcpZCNAcwz1fe8lLPPps) ![HSL](https://private-user-images.githubusercontent.com/113850295/390854730-7aade718-a1c2-49b0-b593-adacdc8e6b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDM2MTgsIm5iZiI6MTczMjg0MzMxOCwicGF0aCI6Ii8xMTM4NTAyOTUvMzkwODU0NzMwLTdhYWRlNzE4LWExYzItNDliMC1iNTkzLWFkYWNkYzhlNmIwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwMTIxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjg0YTRiYTc5MjFjNzVkNjVmZWFmYTAzM2Y3MGNhOTFjYzljMWI1OTg0ZDZiMDgwMTQ0MjM0YzI4ZDhkZTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rlp_nRrwVipTyFFY7HSMdjAbEjFJV-llCAAx_0_P1ok) ![HSV9](https://private-user-images.githubusercontent.com/113850295/390855216-96e43e23-a3f9-4bb7-a83d-1c7ce05c8551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDM2MTgsIm5iZiI6MTczMjg0MzMxOCwicGF0aCI6Ii8xMTM4NTAyOTUvMzkwODU1MjE2LTk2ZTQzZTIzLWEzZjktNGJiNy1hODNkLTFjN2NlMDVjODU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwMTIxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2IzZjZmNDQxNTYxMDA3NzQyNDM4ODljODc4ZTMzNDU5NzQ4N2Q1MjVmOWMzMzBhMWQ0OTI1YzIyODAzMjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LYNxuXWBtPFhvFxxRfxsFrpaNivA_DWoUBYzlcDGmuA)
> 
> Q3：如果使用HSL进行代替是否可行？ A3：可行，但是效果不如HVI好。这点您也可以下载我们的代码，将图像转换成HSL颜色空间进行训练，可以更直观的看到性能上的区别。我们认为颜色空间对一个模型提取信息的能力影响是非常大的，因为不同颜色空间的分布都有区别。而受限于存储图像对sRGB的依赖性，我们只能设计一个新的更接近sRGB分布，但又有亮度与颜色解耦的功能性特征的颜色空间。
> 
> 希望这些回答对你有帮助。如果你认为有用也可以点点star，我们后续可能会有更新。

理解了，感谢作者如此详细的解答！😄
