### ISSUE TITLE
HVI线性变换

### ISSUE THREAD

**Issue by LQchen1** [Fediory/HVI-CIDNet#45]
您好，我在看完论文之后，觉得这篇论文的想法很棒，但是有个问题想请教作者，就是我觉得现在的HV的范围是[-1,1]，这是否限制了后续神经网络的激活函数的选用，比如在这篇论文中，你选择了Tanh激活函数，我尝试把得到的HV直接做线性变换，比如在RGB转HVI的时候H=0.5*（H+1）；V=0.5*（V+1），在PHVI函数hvi转rgb时，H = 2*H-1；V = 2*V-1；然后将模型的激活函数改成GELU；我发现模型性能会明显下降，这是什么原因呢？另外，我还做了一个有趣的实验，比如Retinexformer+HVI色彩空间，我直接将HVI色彩空间放到Retinexformer模型中，我发现即使他们的模型使用的是GELU这样对负值有抑制作用的激活函数，模型效果会比HVI线性变换到[0,1]的效果好。

**Comment by LQchen1** [comment]
我之前想的是在正交函数cos2π和sin2π上做改进，换一组正交基函数，使其输出的值域在[0,1]之间，但我深入了解HSV空间后，考虑到hue的连续性和色彩的均匀性，我感觉cos2π和sin2π是最优解，我数学功底不太好，所以后来选择直接暴力的直接对H和V进行线性变换。

**Comment by Fediory** [comment]
因为我不太知道你的完整代码，所以也不是很确定你这个线性映射变差的原因。一种可能是，你在HVIT里乘以0.5，相当于一个缩放操作，导致数值变小，精度下降。但有一点可以肯定的是，选择GELU激活函数不需要进行任何线性映射。因为这个激活函数是在特征层应用的，前面的卷积层在提取特征的时候是完全有能力一步到位，映射到正数。

**Comment by Fediory** [comment]
对于是不是输出值域在[0,1]之间就一定会让效果变好，这一点我们没有做更多的实验，因此我没办法解释

**Comment by LQchen1** [comment]
![image](https://github.com/user-attachments/assets/34c36fcf-30e3-4fed-9cd8-18541fe22df8)
感谢作者的回答，我也试过[0,2]的值域，感觉也会比原始的差一些，从直觉上来说，由于HV分支的输入部分是HVI整个图像的信息，如果保持每个维度数值上的一致性，结果至少应该不会变差，另外，我想请问作者有没有尝试其他激活函数？还是在整个实验过程中都使用了Tanh（）

**Comment by Fediory** [comment]
每个维度数值上的一致性，是指的数据都分布在[0,1]?
不过我看你的代码的确有一些问题，你需要在clip上都改为0-1clip。

我们尝试过GELU等激活函数，但是最后选择了tanh。因为我们不仅找到了tanh在一些数据统计规律上的优越性，而且实验证明这个激活函数的确收敛的最好，但缺点是容易梯度爆炸。

**Comment by LQchen1** [comment]
Q1：是的，我感觉这样也许会更容易模型的训练。另外对于你说的我需要在clip上都改为0-1clip。我是这样做的，我如果在HVIT变换的时候进行了线性变换，那么我在逆变换的时候，再将HV的值域逆线性变换为[-1,1]，所以不需要改成0-1clip吧，

**Comment by LQchen1** [comment]
另外我想问一下GELU和tanh之间对于模型性能的差距有多少呢

**Comment by LQchen1** [comment]
还有一个事情我想问一下大佬，我现在的模型在lol-v1和v2-syn上都取得了不错的效果，但在v2-real上面的psnr值一直效果不好，ssim还不错，我更改了很多次超参，观看日志发现模型在训练前中期就达到了最佳的PSNR值，这个是不是因为模型参数量不够的原因
![image](https://github.com/user-attachments/assets/5d14e9c0-7102-4317-a679-c702cad0d619)

**Comment by Fediory** [comment]
> 还有一个事情我想问一下大佬，我现在的模型在lol-v1和v2-syn上都取得了不错的效果，但在v2-real上面的psnr值一直效果不好，ssim还不错，我更改了很多次超参，观看日志发现模型在训练前中期就达到了最佳的PSNR值，这个是不是因为模型参数量不够的原因

我不知道如何针对你们的方法训练出最好的模型，我只能给出我们在LOLv2训练出最好的模型时候的参数。
HVI_loss=1.，P_loss=0.01，其余均为0。
使用3090显卡。
以及\alpha_h = 0.8.

**Comment by LQchen1** [comment]
好的，谢谢大佬。

**Comment by LQchen1** [comment]
alpha_h是指这个参数吗？是只在测试的时候用它吗？训练的时候为1
![image](https://github.com/user-attachments/assets/b3bbda5b-4cc3-43f6-ad15-69e9ce425230)

**Comment by LQchen1** [comment]
我的代码是基于另外一个代码开发的，没有看到你在验证的时候alpha的调节。确实很有效果，在验证的时候将alpha改成0.8的结果
![image](https://github.com/user-attachments/assets/f16cfcc7-560c-44d5-b6c6-fa510bf0a3aa)

**Comment by Fediory** [comment]
有个小问题，你的截图是在LOLv2-real上测试的吗

**Comment by Fediory** [comment]
这个理由其实很复杂，你可以简单地理解为HVI对世界的模拟性更强，在训练后可以仅通过简单的线性变换就达到更好的结果。
这两个系数分别是alpha_v和alpha_s，在论文中都有提到。
但是我们没有特别详细对这两个系数展开，因为这其实是HSV做到的，而不是HVI。HVI只是HSV的改良版。

**Comment by LQchen1** [comment]
> 有一个小问题，你的截图是在 LOLv2-real 上测试的吗

是的。这是加上了alpha=0.8超参之后的结果

**Comment by LQchen1** [comment]
> 这个理由其实很复杂，你可以简单地理解为HVI对世界的模拟性更强，在训练后可以仅通过简单的线性变换就达到更好的结果。 这两个系数分别是alpha_v和alpha_s，在论文中都有提到。 但是我们没有特别详细对这两个系数展开，因为这其实是HSV做到的，而不是HVI。HVI只是HSV的改良版。

好的，感谢大佬，我再去详细看一下论文。

**Comment by Fediory** [comment]
首先我来总结一下我们论文中提到的所有参数。
在HVI颜色空间中，包括k，gamma_G和gamma_B，DT。
在PHVIT中，包括alpha_v和alpha_s。
其余则是神经网络中的参数。

这些参数里，HVI中的是用来学习颜色空间级别的数据集分布。
神经网络中，是用来学习增亮和去噪过程。
那么，PHVIT中，是用来手动调整我们想要的视觉效果。
也就是说实际上，alpha_v和alpha_s就相当于大模型的prompt。

而对于HVI颜色空间来讲，k，gamma_G和gamma_B，DT全部为可学习的。
PHVIT逆变换中，则是我们可以进行人为干预，手动操作的过程。
所以PHVIT其实不属于HVI颜色空间级别的操作，他在论文中的目的仅仅是转换为sRGB图像的工具。

**Comment by Fediory** [comment]
但是我也认为alpha_v和alpha_s可以在无监督训练和zero-shot中发挥很大作用，可以设定成两个参数用于训练。
因为他们正是为了提升泛化能力而存在的。

**Comment by LQchen1** [comment]
明白了，非常感谢大佬解惑。
