### ISSUE TITLE
关于HVIT函数的问题

### ISSUE THREAD

**Issue by 2402227288** [Fediory/HVI-CIDNet#46]
![image](https://github.com/user-attachments/assets/42bee2c6-fda1-47a9-a939-dc553a1fe90a)
在看代码有些地方有疑惑，我并没有看到Py和DT函数在这个代码中，hue我理解为色相，但是为什么h和v，对应的cos(2*pi*Py),在代码中Py为hue呢

**Comment by 2402227288** [comment]
同时yG和yB我好像也没有看到

**Comment by Fediory** [comment]
DT函数和yG和yB的默认值我们在论文中都有写。我们选择的这些默认值使得在代码中不用进行任何额外操作，简化了逻辑。
如果你要按照论文中调整这些参数，直接看代码修改应该也很简单。

**Comment by 2402227288** [comment]
但我好像并没有看到默认值，论文有更新吗？

**Comment by 2402227288** [comment]
hue[img[:,2]==value] = 4.0 + ( (img[:,0]-img[:,1]) / (value - img_min + eps)) [img[:,2]==value] 
        hue[img[:,1]==value] = 2.0 + ( (img[:,2]-img[:,0]) / (value - img_min + eps)) [img[:,1]==value]
        hue[img[:,0]==value] = (0.0 + ((img[:,1]-img[:,2]) / (value - img_min + eps)) [img[:,0]==value]) % 6
![image](https://github.com/user-attachments/assets/79c4aab9-ce20-4170-b329-59e4ce2a6db4)
这里代码和文章中推导好像不大一样

**Comment by Fediory** [comment]
代码是匹配的，你把hue除以6后就是与论文中一样的。
DT默认为1
yG和yB默认为1/3和2/3

**Comment by Fediory** [comment]
我们在v1版本的论文中提到过这个默认值

**Comment by 2402227288** [comment]
啊这样啊，那现在更新的文章确实没有，十分感谢！
