### ISSUE TITLE
作者您好，您方便公布一个对比方法的结果图吗，感谢您在低光增强任务的贡献

### ISSUE THREAD

**Issue by ooojiang** [Fediory/HVI-CIDNet#47]

**Comment by Fediory** [comment]
你的意思是，你想要其它方法的output图像？

**Comment by ooojiang** [comment]
嗯嗯，是的😊非常感谢





---原始邮件---
发件人: "Fediory ***@***.***&gt;
发送时间: 2024年12月18日(周三) 晚上10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Fediory/HVI-CIDNet] 作者您好，您方便公布一个对比方法的结果图吗，感谢您在低光增强任务的贡献 (Issue #47)




 
你的意思是，你想要其它方法的output图像？

**Comment by ooojiang** [comment]
是的，如果不方便也没事，非常感谢您能回复
