### ISSUE TITLE
关于数据集的布置arrange问题：

### ISSUE THREAD

**Issue by ZhangWeihao3014** [Fediory/HVI-CIDNet#5]
看作者关于数据集中文件夹的布置要求。但是作者应该是进行了自己的调整，因为对比原始下载下来的LoLv1和LoLv2和作者的文件夹树不一样。但是作者对于自己调整过的树说明的不是很明确，例如LoLv1中有很多文件夹叫做low和high，哪一个是放在最外层的？并且只有叫eval15的文件夹，没有叫eval115的文件夹。烦请作者解答一下，也可能是帮助你的readme更加完善！

**Comment by ZhangWeihao3014** [comment]
star已给。

**Comment by Fediory** [comment]
感谢你的star。对于这个问题，是我们readme写的时候对齐没有做好。我们的LOLv1和v2两个数据集均不需要调整文件树，下载即用。目前我们已经修改了Readme.md的dataset arrange部分，感谢你的完善！
