### ISSUE TITLE
如何训练无配对的数据集

### ISSUE THREAD

**Issue by zgbuct** [Fediory/HVI-CIDNet#6]
你好，请问是怎么训练无配对的数据集的啊

**Comment by Fediory** [comment]
你好，HVI-CIDNet是一个有监督的模型，对于无配对数据集，我们没办法进行训练。因此，我们是在配对数据集上进行训练后，得到weights，并用无配对数据集进行测试。
如果觉得我们的repo有用的话，帮点个star支持一下！谢谢

**Comment by zgbuct** [comment]
已经给星啦
