### ISSUE TITLE
Pretrained weights availability outside China

### ISSUE THREAD

**Issue by korotaS** [Fediory/HVI-CIDNet#7]
Hi!
I am trying to download pretrained weights for your models on Baidu Pan but they can be downloaded only for registered users and I can't register from outside of China on Baidu. 
Can you please tell whether the weights will be available on some other platform like Google Drive? 
Thanks!

**Comment by Fediory** [comment]
Thank you for supporting our work. We will be synchronizing all Baidu Pan content to One Drive in the near future (about 3days). If you find our repo useful for your work, please give star, thanks!

**Comment by Fediory** [comment]
We have already synchronized all Baidu Pan datasets and weights to One Drive now! Thanks your issue.

**Comment by zelenooki87** [comment]
Onedrive weights locked by password?

**Comment by zelenooki87** [comment]
yeah, I saw later. I am sorry
Thank for wonderful project.
