### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by girish445ai** [Fediory/HVI-CIDNet#8]
Hi ,
Can you please provide one drive or Google drive links for the pre-trained  models .

**Comment by Fediory** [comment]
Thank you for supporting our work. We will be synchronizing all Baidu Pan content to One Drive in the near future (about today). If you find our repo useful for your work, please give star, thanks!

**Comment by Fediory** [comment]
We have already synchronized all Baidu Pan datasets and weights to One Drive now! Thanks your issue.
