### ISSUE TITLE
论文原理问题

### ISSUE THREAD

**Issue by jhxiang** [Fediory/HVI-CIDNet#9]
谢谢作者的优质工作。关于论文原理方面，我有两个问题：
1、 ColorPerceptual map Pγ的设计准则是什么？ DT这个变量是否表示色彩呢？
2、IEL和CDL这样设计的依据是什么呢？
希望能解答下我的疑惑，谢谢！

**Comment by Fediory** [comment]
[Appendix.pdf](https://github.com/Fediory/HVI-CIDNet/files/15218748/Appendix.pdf)
这是我们论文的Appendix，希望对你有帮助！

**Comment by jhxiang** [comment]
非常感谢，我学习了一下。论文原理本质上是将sRGB空间进行点对点映射到HVI空间，DT=T(Pγ)本质上是Hue的映射，而Ck这个参数我理解是在低光条件下保证图像色彩的丰富性？不知道我这样理解对吗？

**Comment by Fediory** [comment]
您的理解比较准确。补充说明一下，HVI的motivation其中之一就是对sRGB进行单射且满射的变换（一一对应），这是曾经的颜色空间（or 颜色模型）没有的。

Pγ中的两个参数是对Hue的线性变换，直观上就是将Hue线性拉伸，目的是为了学习数据集（相机）在RGB三轴信号的敏感度。T(x)函数则是自定义的映射，方便迁移到其它任务中。

Ck中的k，直观上来讲，k越大，图像中被神经网络“看到”的细节就越多，同时噪声也会增大，方便卷积层的kernel拟合到更好的值，我倾向于将k解释为可视“信噪比”。如果您有什么其它理解，也欢迎提出！

**Comment by jhxiang** [comment]
很赞，已star！
